#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AceNews.Old_Code.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AceNews")]
	public partial class NewsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNewsKeywords(NewsKeywords instance);
    partial void UpdateNewsKeywords(NewsKeywords instance);
    partial void DeleteNewsKeywords(NewsKeywords instance);
    partial void InsertNews(News instance);
    partial void UpdateNews(News instance);
    partial void DeleteNews(News instance);
    #endregion
		
		public NewsDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AceNewsConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NewsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<vNewsComments> vNewsComments
		{
			get
			{
				return this.GetTable<vNewsComments>();
			}
		}
		
		public System.Data.Linq.Table<vNewsRelatedNews> vNewsRelatedNews
		{
			get
			{
				return this.GetTable<vNewsRelatedNews>();
			}
		}
		
		public System.Data.Linq.Table<NewsKeywords> NewsKeywords
		{
			get
			{
				return this.GetTable<NewsKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vNewsKeywords> vNewsKeywords
		{
			get
			{
				return this.GetTable<vNewsKeywords>();
			}
		}
		
		public System.Data.Linq.Table<vLatestNews> vLatestNews
		{
			get
			{
				return this.GetTable<vLatestNews>();
			}
		}
		
		public System.Data.Linq.Table<News> News
		{
			get
			{
				return this.GetTable<News>();
			}
		}
		
		public System.Data.Linq.Table<vNews> vNews
		{
			get
			{
				return this.GetTable<vNews>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsComments")]
	public partial class vNewsComments
	{
		
		private int _Code;
		
		private int _NewsCode;
		
		private string _Name;
		
		private string _Email;
		
		private string _SDate;
		
		private string _Status;
		
		public vNewsComments()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCode", DbType="Int NOT NULL")]
		public int NewsCode
		{
			get
			{
				return this._NewsCode;
			}
			set
			{
				if ((this._NewsCode != value))
				{
					this._NewsCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(500)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDate", DbType="VarChar(10)")]
		public string SDate
		{
			get
			{
				return this._SDate;
			}
			set
			{
				if ((this._SDate != value))
				{
					this._SDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(500)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsRelatedNews")]
	public partial class vNewsRelatedNews
	{
		
		private int _Code;
		
		private int _NewsCode;
		
		private string _Title;
		
		private int _RelatedNewsCode;
		
		private string _PicFile1;
		
		private string _PicFile2;
		
		public vNewsRelatedNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCode", DbType="Int NOT NULL")]
		public int NewsCode
		{
			get
			{
				return this._NewsCode;
			}
			set
			{
				if ((this._NewsCode != value))
				{
					this._NewsCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelatedNewsCode", DbType="Int NOT NULL")]
		public int RelatedNewsCode
		{
			get
			{
				return this._RelatedNewsCode;
			}
			set
			{
				if ((this._RelatedNewsCode != value))
				{
					this._RelatedNewsCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile1", DbType="NVarChar(200)")]
		public string PicFile1
		{
			get
			{
				return this._PicFile1;
			}
			set
			{
				if ((this._PicFile1 != value))
				{
					this._PicFile1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile2", DbType="NVarChar(200)")]
		public string PicFile2
		{
			get
			{
				return this._PicFile2;
			}
			set
			{
				if ((this._PicFile2 != value))
				{
					this._PicFile2 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NewsKeywords")]
	public partial class NewsKeywords : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private int _NewsCode;
		
		private string _Keyword;
		
		private EntityRef<News> _News;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNewsCodeChanging(int value);
    partial void OnNewsCodeChanged();
    partial void OnKeywordChanging(string value);
    partial void OnKeywordChanged();
    #endregion
		
		public NewsKeywords()
		{
			this._News = default(EntityRef<News>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCode", DbType="Int NOT NULL")]
		public int NewsCode
		{
			get
			{
				return this._NewsCode;
			}
			set
			{
				if ((this._NewsCode != value))
				{
					if (this._News.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNewsCodeChanging(value);
					this.SendPropertyChanging();
					this._NewsCode = value;
					this.SendPropertyChanged("NewsCode");
					this.OnNewsCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this.OnKeywordChanging(value);
					this.SendPropertyChanging();
					this._Keyword = value;
					this.SendPropertyChanged("Keyword");
					this.OnKeywordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="New_NewsKeywords", Storage="_News", ThisKey="NewsCode", OtherKey="Code", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public News News
		{
			get
			{
				return this._News.Entity;
			}
			set
			{
				News previousValue = this._News.Entity;
				if (((previousValue != value) 
							|| (this._News.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._News.Entity = null;
						previousValue.NewsKeywords.Remove(this);
					}
					this._News.Entity = value;
					if ((value != null))
					{
						value.NewsKeywords.Add(this);
						this._NewsCode = value.Code;
					}
					else
					{
						this._NewsCode = default(int);
					}
					this.SendPropertyChanged("News");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNewsKeywords")]
	public partial class vNewsKeywords
	{
		
		private int _Code;
		
		private int _NewsCode;
		
		private string _Keyword;
		
		public vNewsKeywords()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsCode", DbType="Int NOT NULL")]
		public int NewsCode
		{
			get
			{
				return this._NewsCode;
			}
			set
			{
				if ((this._NewsCode != value))
				{
					this._NewsCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keyword", DbType="NVarChar(100)")]
		public string Keyword
		{
			get
			{
				return this._Keyword;
			}
			set
			{
				if ((this._Keyword != value))
				{
					this._Keyword = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vLatestNews")]
	public partial class vLatestNews
	{
		
		private int _Code;
		
		private string _NewsNumber;
		
		private System.DateTime _NewsDate;
		
		private string _Title;
		
		private string _SoTitr;
		
		private string _PicFile1;
		
		private string _Abstract;
		
		private System.Nullable<bool> _ShowInNews;
		
		private bool _ShowInTelex;
		
		private int _Priority;
		
		private System.Nullable<int> _HCContentTypeCode;
		
		private string _ContentType;
		
		private string _PicFile2;
		
		private System.Nullable<int> _HCNewsCatCode;
		
		private string _NDate;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _HCNewsTypeCode;
		
		public vLatestNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsNumber", DbType="NVarChar(100)")]
		public string NewsNumber
		{
			get
			{
				return this._NewsNumber;
			}
			set
			{
				if ((this._NewsNumber != value))
				{
					this._NewsNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime NOT NULL")]
		public System.DateTime NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTitr", DbType="NVarChar(1000)")]
		public string SoTitr
		{
			get
			{
				return this._SoTitr;
			}
			set
			{
				if ((this._SoTitr != value))
				{
					this._SoTitr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile1", DbType="NVarChar(200)")]
		public string PicFile1
		{
			get
			{
				return this._PicFile1;
			}
			set
			{
				if ((this._PicFile1 != value))
				{
					this._PicFile1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abstract", DbType="NVarChar(MAX)")]
		public string Abstract
		{
			get
			{
				return this._Abstract;
			}
			set
			{
				if ((this._Abstract != value))
				{
					this._Abstract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInNews", DbType="Bit")]
		public System.Nullable<bool> ShowInNews
		{
			get
			{
				return this._ShowInNews;
			}
			set
			{
				if ((this._ShowInNews != value))
				{
					this._ShowInNews = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInTelex", DbType="Bit NOT NULL")]
		public bool ShowInTelex
		{
			get
			{
				return this._ShowInTelex;
			}
			set
			{
				if ((this._ShowInTelex != value))
				{
					this._ShowInTelex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCContentTypeCode", DbType="Int")]
		public System.Nullable<int> HCContentTypeCode
		{
			get
			{
				return this._HCContentTypeCode;
			}
			set
			{
				if ((this._HCContentTypeCode != value))
				{
					this._HCContentTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContentType", DbType="NVarChar(500)")]
		public string ContentType
		{
			get
			{
				return this._ContentType;
			}
			set
			{
				if ((this._ContentType != value))
				{
					this._ContentType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile2", DbType="NVarChar(200)")]
		public string PicFile2
		{
			get
			{
				return this._PicFile2;
			}
			set
			{
				if ((this._PicFile2 != value))
				{
					this._PicFile2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCNewsCatCode", DbType="Int")]
		public System.Nullable<int> HCNewsCatCode
		{
			get
			{
				return this._HCNewsCatCode;
			}
			set
			{
				if ((this._HCNewsCatCode != value))
				{
					this._HCNewsCatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NDate", DbType="VarChar(10)")]
		public string NDate
		{
			get
			{
				return this._NDate;
			}
			set
			{
				if ((this._NDate != value))
				{
					this._NDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCNewsTypeCode", DbType="Int")]
		public System.Nullable<int> HCNewsTypeCode
		{
			get
			{
				return this._HCNewsTypeCode;
			}
			set
			{
				if ((this._HCNewsTypeCode != value))
				{
					this._HCNewsTypeCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.News")]
	public partial class News : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Code;
		
		private string _NewsNumber;
		
		private System.DateTime _NewsDate;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private string _CreateIP;
		
		private string _EditIP;
		
		private string _PicFile1;
		
		private string _PicFile2;
		
		private string _PicFileWide;
		
		private string _Title;
		
		private System.Nullable<int> _HCNewsCatCode;
		
		private System.Nullable<int> _HCContentTypeCode;
		
		private System.Nullable<int> _HCNewsTypeCode;
		
		private string _SoTitr;
		
		private int _Priority;
		
		private string _Abstract;
		
		private string _NewsBody;
		
		private System.Nullable<bool> _ShowInNews;
		
		private System.Nullable<bool> _ShowInTelex;
		
		private System.Nullable<bool> _Special;
		
		private string _PicComment;
		
		private string _SourceLink;
		
		private string _Translator;
		
		private string _Keywords;
		
		private string _tmpCode;
		
		private System.Nullable<bool> _EditorChoice;
		
		private System.Nullable<bool> _ShowPic;
		
		private EntitySet<NewsKeywords> _NewsKeywords;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(int value);
    partial void OnCodeChanged();
    partial void OnNewsNumberChanging(string value);
    partial void OnNewsNumberChanged();
    partial void OnNewsDateChanging(System.DateTime value);
    partial void OnNewsDateChanged();
    partial void OnCreateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreateDateChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnCreateIPChanging(string value);
    partial void OnCreateIPChanged();
    partial void OnEditIPChanging(string value);
    partial void OnEditIPChanged();
    partial void OnPicFile1Changing(string value);
    partial void OnPicFile1Changed();
    partial void OnPicFile2Changing(string value);
    partial void OnPicFile2Changed();
    partial void OnPicFileWideChanging(string value);
    partial void OnPicFileWideChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnHCNewsCatCodeChanging(System.Nullable<int> value);
    partial void OnHCNewsCatCodeChanged();
    partial void OnHCContentTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCContentTypeCodeChanged();
    partial void OnHCNewsTypeCodeChanging(System.Nullable<int> value);
    partial void OnHCNewsTypeCodeChanged();
    partial void OnSoTitrChanging(string value);
    partial void OnSoTitrChanged();
    partial void OnPriorityChanging(int value);
    partial void OnPriorityChanged();
    partial void OnAbstractChanging(string value);
    partial void OnAbstractChanged();
    partial void OnNewsBodyChanging(string value);
    partial void OnNewsBodyChanged();
    partial void OnShowInNewsChanging(System.Nullable<bool> value);
    partial void OnShowInNewsChanged();
    partial void OnShowInTelexChanging(System.Nullable<bool> value);
    partial void OnShowInTelexChanged();
    partial void OnSpecialChanging(System.Nullable<bool> value);
    partial void OnSpecialChanged();
    partial void OnPicCommentChanging(string value);
    partial void OnPicCommentChanged();
    partial void OnSourceLinkChanging(string value);
    partial void OnSourceLinkChanged();
    partial void OnTranslatorChanging(string value);
    partial void OnTranslatorChanged();
    partial void OnKeywordsChanging(string value);
    partial void OnKeywordsChanged();
    partial void OntmpCodeChanging(string value);
    partial void OntmpCodeChanged();
    partial void OnEditorChoiceChanging(System.Nullable<bool> value);
    partial void OnEditorChoiceChanged();
    partial void OnShowPicChanging(System.Nullable<bool> value);
    partial void OnShowPicChanged();
    #endregion
		
		public News()
		{
			this._NewsKeywords = new EntitySet<NewsKeywords>(new Action<NewsKeywords>(this.attach_NewsKeywords), new Action<NewsKeywords>(this.detach_NewsKeywords));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsNumber", DbType="NVarChar(100)")]
		public string NewsNumber
		{
			get
			{
				return this._NewsNumber;
			}
			set
			{
				if ((this._NewsNumber != value))
				{
					this.OnNewsNumberChanging(value);
					this.SendPropertyChanging();
					this._NewsNumber = value;
					this.SendPropertyChanged("NewsNumber");
					this.OnNewsNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime NOT NULL")]
		public System.DateTime NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this.OnNewsDateChanging(value);
					this.SendPropertyChanging();
					this._NewsDate = value;
					this.SendPropertyChanged("NewsDate");
					this.OnNewsDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateIP", DbType="VarChar(50)")]
		public string CreateIP
		{
			get
			{
				return this._CreateIP;
			}
			set
			{
				if ((this._CreateIP != value))
				{
					this.OnCreateIPChanging(value);
					this.SendPropertyChanging();
					this._CreateIP = value;
					this.SendPropertyChanged("CreateIP");
					this.OnCreateIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditIP", DbType="VarChar(50)")]
		public string EditIP
		{
			get
			{
				return this._EditIP;
			}
			set
			{
				if ((this._EditIP != value))
				{
					this.OnEditIPChanging(value);
					this.SendPropertyChanging();
					this._EditIP = value;
					this.SendPropertyChanged("EditIP");
					this.OnEditIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile1", DbType="NVarChar(200)")]
		public string PicFile1
		{
			get
			{
				return this._PicFile1;
			}
			set
			{
				if ((this._PicFile1 != value))
				{
					this.OnPicFile1Changing(value);
					this.SendPropertyChanging();
					this._PicFile1 = value;
					this.SendPropertyChanged("PicFile1");
					this.OnPicFile1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile2", DbType="NVarChar(200)")]
		public string PicFile2
		{
			get
			{
				return this._PicFile2;
			}
			set
			{
				if ((this._PicFile2 != value))
				{
					this.OnPicFile2Changing(value);
					this.SendPropertyChanging();
					this._PicFile2 = value;
					this.SendPropertyChanged("PicFile2");
					this.OnPicFile2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFileWide", DbType="NVarChar(200)")]
		public string PicFileWide
		{
			get
			{
				return this._PicFileWide;
			}
			set
			{
				if ((this._PicFileWide != value))
				{
					this.OnPicFileWideChanging(value);
					this.SendPropertyChanging();
					this._PicFileWide = value;
					this.SendPropertyChanged("PicFileWide");
					this.OnPicFileWideChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCNewsCatCode", DbType="Int")]
		public System.Nullable<int> HCNewsCatCode
		{
			get
			{
				return this._HCNewsCatCode;
			}
			set
			{
				if ((this._HCNewsCatCode != value))
				{
					this.OnHCNewsCatCodeChanging(value);
					this.SendPropertyChanging();
					this._HCNewsCatCode = value;
					this.SendPropertyChanged("HCNewsCatCode");
					this.OnHCNewsCatCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCContentTypeCode", DbType="Int")]
		public System.Nullable<int> HCContentTypeCode
		{
			get
			{
				return this._HCContentTypeCode;
			}
			set
			{
				if ((this._HCContentTypeCode != value))
				{
					this.OnHCContentTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCContentTypeCode = value;
					this.SendPropertyChanged("HCContentTypeCode");
					this.OnHCContentTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCNewsTypeCode", DbType="Int")]
		public System.Nullable<int> HCNewsTypeCode
		{
			get
			{
				return this._HCNewsTypeCode;
			}
			set
			{
				if ((this._HCNewsTypeCode != value))
				{
					this.OnHCNewsTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._HCNewsTypeCode = value;
					this.SendPropertyChanged("HCNewsTypeCode");
					this.OnHCNewsTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTitr", DbType="NVarChar(1000)")]
		public string SoTitr
		{
			get
			{
				return this._SoTitr;
			}
			set
			{
				if ((this._SoTitr != value))
				{
					this.OnSoTitrChanging(value);
					this.SendPropertyChanging();
					this._SoTitr = value;
					this.SendPropertyChanged("SoTitr");
					this.OnSoTitrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this.OnPriorityChanging(value);
					this.SendPropertyChanging();
					this._Priority = value;
					this.SendPropertyChanged("Priority");
					this.OnPriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abstract", DbType="NVarChar(MAX)")]
		public string Abstract
		{
			get
			{
				return this._Abstract;
			}
			set
			{
				if ((this._Abstract != value))
				{
					this.OnAbstractChanging(value);
					this.SendPropertyChanging();
					this._Abstract = value;
					this.SendPropertyChanged("Abstract");
					this.OnAbstractChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsBody", DbType="NVarChar(MAX)")]
		public string NewsBody
		{
			get
			{
				return this._NewsBody;
			}
			set
			{
				if ((this._NewsBody != value))
				{
					this.OnNewsBodyChanging(value);
					this.SendPropertyChanging();
					this._NewsBody = value;
					this.SendPropertyChanged("NewsBody");
					this.OnNewsBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInNews", DbType="Bit")]
		public System.Nullable<bool> ShowInNews
		{
			get
			{
				return this._ShowInNews;
			}
			set
			{
				if ((this._ShowInNews != value))
				{
					this.OnShowInNewsChanging(value);
					this.SendPropertyChanging();
					this._ShowInNews = value;
					this.SendPropertyChanged("ShowInNews");
					this.OnShowInNewsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInTelex", DbType="Bit")]
		public System.Nullable<bool> ShowInTelex
		{
			get
			{
				return this._ShowInTelex;
			}
			set
			{
				if ((this._ShowInTelex != value))
				{
					this.OnShowInTelexChanging(value);
					this.SendPropertyChanging();
					this._ShowInTelex = value;
					this.SendPropertyChanged("ShowInTelex");
					this.OnShowInTelexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Special", DbType="Bit")]
		public System.Nullable<bool> Special
		{
			get
			{
				return this._Special;
			}
			set
			{
				if ((this._Special != value))
				{
					this.OnSpecialChanging(value);
					this.SendPropertyChanging();
					this._Special = value;
					this.SendPropertyChanged("Special");
					this.OnSpecialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicComment", DbType="NVarChar(500)")]
		public string PicComment
		{
			get
			{
				return this._PicComment;
			}
			set
			{
				if ((this._PicComment != value))
				{
					this.OnPicCommentChanging(value);
					this.SendPropertyChanging();
					this._PicComment = value;
					this.SendPropertyChanged("PicComment");
					this.OnPicCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceLink", DbType="NVarChar(500)")]
		public string SourceLink
		{
			get
			{
				return this._SourceLink;
			}
			set
			{
				if ((this._SourceLink != value))
				{
					this.OnSourceLinkChanging(value);
					this.SendPropertyChanging();
					this._SourceLink = value;
					this.SendPropertyChanged("SourceLink");
					this.OnSourceLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Translator", DbType="NVarChar(500)")]
		public string Translator
		{
			get
			{
				return this._Translator;
			}
			set
			{
				if ((this._Translator != value))
				{
					this.OnTranslatorChanging(value);
					this.SendPropertyChanging();
					this._Translator = value;
					this.SendPropertyChanged("Translator");
					this.OnTranslatorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords", DbType="NVarChar(500)")]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this.OnKeywordsChanging(value);
					this.SendPropertyChanging();
					this._Keywords = value;
					this.SendPropertyChanged("Keywords");
					this.OnKeywordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tmpCode", DbType="NVarChar(50)")]
		public string tmpCode
		{
			get
			{
				return this._tmpCode;
			}
			set
			{
				if ((this._tmpCode != value))
				{
					this.OntmpCodeChanging(value);
					this.SendPropertyChanging();
					this._tmpCode = value;
					this.SendPropertyChanged("tmpCode");
					this.OntmpCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorChoice", DbType="Bit")]
		public System.Nullable<bool> EditorChoice
		{
			get
			{
				return this._EditorChoice;
			}
			set
			{
				if ((this._EditorChoice != value))
				{
					this.OnEditorChoiceChanging(value);
					this.SendPropertyChanging();
					this._EditorChoice = value;
					this.SendPropertyChanged("EditorChoice");
					this.OnEditorChoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowPic", DbType="Bit")]
		public System.Nullable<bool> ShowPic
		{
			get
			{
				return this._ShowPic;
			}
			set
			{
				if ((this._ShowPic != value))
				{
					this.OnShowPicChanging(value);
					this.SendPropertyChanging();
					this._ShowPic = value;
					this.SendPropertyChanged("ShowPic");
					this.OnShowPicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="New_NewsKeywords", Storage="_NewsKeywords", ThisKey="Code", OtherKey="NewsCode")]
		public EntitySet<NewsKeywords> NewsKeywords
		{
			get
			{
				return this._NewsKeywords;
			}
			set
			{
				this._NewsKeywords.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NewsKeywords(NewsKeywords entity)
		{
			this.SendPropertyChanging();
			entity.News = this;
		}
		
		private void detach_NewsKeywords(NewsKeywords entity)
		{
			this.SendPropertyChanging();
			entity.News = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vNews")]
	public partial class vNews
	{
		
		private int _Code;
		
		private string _NewsNumber;
		
		private string _NDate;
		
		private string _Title;
		
		private string _CatName;
		
		private System.DateTime _NewsDate;
		
		private System.Nullable<bool> _ShowInTelex;
		
		private System.Nullable<bool> _ShowInNews;
		
		private string _NewsBody;
		
		private string _Abstract;
		
		private string _PicFile1;
		
		private string _SoTitr;
		
		private int _Priority;
		
		private System.Nullable<bool> _Special;
		
		private string _PicFile2;
		
		private string _PicFileWide;
		
		private System.Nullable<int> _HCContentTypeCode;
		
		private System.Nullable<int> _HCNewsCatCode;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<bool> _EditorChoice;
		
		private System.Nullable<int> _HCNewsTypeCode;
		
		private System.Nullable<bool> _ShowPic;
		
		private string _Keywords;
		
		public vNews()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Int NOT NULL")]
		public int Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsNumber", DbType="NVarChar(100)")]
		public string NewsNumber
		{
			get
			{
				return this._NewsNumber;
			}
			set
			{
				if ((this._NewsNumber != value))
				{
					this._NewsNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NDate", DbType="VarChar(10)")]
		public string NDate
		{
			get
			{
				return this._NDate;
			}
			set
			{
				if ((this._NDate != value))
				{
					this._NDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatName", DbType="NVarChar(500)")]
		public string CatName
		{
			get
			{
				return this._CatName;
			}
			set
			{
				if ((this._CatName != value))
				{
					this._CatName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsDate", DbType="DateTime NOT NULL")]
		public System.DateTime NewsDate
		{
			get
			{
				return this._NewsDate;
			}
			set
			{
				if ((this._NewsDate != value))
				{
					this._NewsDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInTelex", DbType="Bit")]
		public System.Nullable<bool> ShowInTelex
		{
			get
			{
				return this._ShowInTelex;
			}
			set
			{
				if ((this._ShowInTelex != value))
				{
					this._ShowInTelex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowInNews", DbType="Bit")]
		public System.Nullable<bool> ShowInNews
		{
			get
			{
				return this._ShowInNews;
			}
			set
			{
				if ((this._ShowInNews != value))
				{
					this._ShowInNews = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewsBody", DbType="NVarChar(MAX)")]
		public string NewsBody
		{
			get
			{
				return this._NewsBody;
			}
			set
			{
				if ((this._NewsBody != value))
				{
					this._NewsBody = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abstract", DbType="NVarChar(MAX)")]
		public string Abstract
		{
			get
			{
				return this._Abstract;
			}
			set
			{
				if ((this._Abstract != value))
				{
					this._Abstract = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile1", DbType="NVarChar(200)")]
		public string PicFile1
		{
			get
			{
				return this._PicFile1;
			}
			set
			{
				if ((this._PicFile1 != value))
				{
					this._PicFile1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTitr", DbType="NVarChar(1000)")]
		public string SoTitr
		{
			get
			{
				return this._SoTitr;
			}
			set
			{
				if ((this._SoTitr != value))
				{
					this._SoTitr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Priority", DbType="Int NOT NULL")]
		public int Priority
		{
			get
			{
				return this._Priority;
			}
			set
			{
				if ((this._Priority != value))
				{
					this._Priority = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Special", DbType="Bit")]
		public System.Nullable<bool> Special
		{
			get
			{
				return this._Special;
			}
			set
			{
				if ((this._Special != value))
				{
					this._Special = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFile2", DbType="NVarChar(200)")]
		public string PicFile2
		{
			get
			{
				return this._PicFile2;
			}
			set
			{
				if ((this._PicFile2 != value))
				{
					this._PicFile2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PicFileWide", DbType="NVarChar(200)")]
		public string PicFileWide
		{
			get
			{
				return this._PicFileWide;
			}
			set
			{
				if ((this._PicFileWide != value))
				{
					this._PicFileWide = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCContentTypeCode", DbType="Int")]
		public System.Nullable<int> HCContentTypeCode
		{
			get
			{
				return this._HCContentTypeCode;
			}
			set
			{
				if ((this._HCContentTypeCode != value))
				{
					this._HCContentTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCNewsCatCode", DbType="Int")]
		public System.Nullable<int> HCNewsCatCode
		{
			get
			{
				return this._HCNewsCatCode;
			}
			set
			{
				if ((this._HCNewsCatCode != value))
				{
					this._HCNewsCatCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditorChoice", DbType="Bit")]
		public System.Nullable<bool> EditorChoice
		{
			get
			{
				return this._EditorChoice;
			}
			set
			{
				if ((this._EditorChoice != value))
				{
					this._EditorChoice = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCNewsTypeCode", DbType="Int")]
		public System.Nullable<int> HCNewsTypeCode
		{
			get
			{
				return this._HCNewsTypeCode;
			}
			set
			{
				if ((this._HCNewsTypeCode != value))
				{
					this._HCNewsTypeCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowPic", DbType="Bit")]
		public System.Nullable<bool> ShowPic
		{
			get
			{
				return this._ShowPic;
			}
			set
			{
				if ((this._ShowPic != value))
				{
					this._ShowPic = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keywords", DbType="NVarChar(500)")]
		public string Keywords
		{
			get
			{
				return this._Keywords;
			}
			set
			{
				if ((this._Keywords != value))
				{
					this._Keywords = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
