<?xml version="1.0" encoding="utf-8"?><Database Name="AceNews" Class="NewspapersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=AceNews;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AceNewsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.vNewspapers" Member="vNewspapers">
    <Type Name="vNewspapers">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NDate" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Newspapers" Member="Newspapers">
    <Type Name="Newspapers">
      <Column Name="Code" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NPDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PicFile" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>